### ISSUE TITLE
Is it possible to change default dir `bin`?

### ISSUE THREAD

**Issue by amr3k** [NICHOLAS85/dynamic-wall#12]
Hi, thanks for this awesome plugin.

All I want is to change the default `$user/bin` to be `$user/.bin` to be hidden for cleaner home directory look.

**Comment by NICHOLAS85** [comment]
Hey! Thanks for trying out my little program. I've created the `bin` branch which should support what you need.
Simply run:
`git clone -b bin https://github.com/NICHOLAS85/dynamic-wall.git`
to clone the branch and to install dynamic-wall into a custom directory use the command:
`./install --install-dir ~/.bin `
Let me know if you run into any kinks! I've tested it on my end and it seems to work perfectly well. I'm going to write it up a bit and eventually merge the custom directory support into master.

**Comment by NICHOLAS85** [comment]
This functionality has now been merged into master.

**Comment by amr3k** [comment]
Thanks man you are awesome
